### PR TITLE
Enhancement changes have been made to the styling and UI

### PR DESCRIPTION
**Pull request by siiddhantt**
# Description

Enhancement changes have been made to the styling and UI.

Fixes # (issue)

## Type of change

- [x] Added buttons with icons for implementing filter feature in future.
- [x] Added the Hacktoberfest 2022 logo/symbol.
- [x] Improvement to the style of the list itself.

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great changes 👏🏻
Just fix this.
Screenshot 2022-09-30 094643

**Comment by siiddhantt** [comment]
Yep got it. Will implement that.

**Comment by siiddhantt** [comment]
I've removed the tags and just imported them as components.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
It's not visible on the deployed site.
Screenshot 2022-09-30 094643

**Comment by siiddhantt** [comment]
Yeah I've removed the tags completely. They can still be used as I've imported them as components It's my first time using Vue, so don't want to implement major changes. 
So I've reverted back to just changes in the style of the list.

**Pull request merged**
